version: '3.8'

services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_URL_IMG=http://localhost:5000/files/
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=https://cmpc-bookapi-production.up.railway.app/
      - VITE_URL_IMG=https://cmpc-bookapi-production.up.railway.app/files/
    networks:
      - app-network
    profiles:
      - production

networks:
  app-network:
    driver: bridge